fulfil: instructors section completed and created docs for students-p…
azoirov/fulfil pull request #4
Opened 2022-11-07 13:34 UTC by MubiynDev

…rojects domain

2022-11-07 13:35 UTC, MubiynDev commented
fulfil: instructors section completed and created docs for students-projects domain

2022-11-09 15:10 UTC, azoirov requested changes

2022-11-09 15:10 UTC, azoirov commented on src/domain/instructors/instructor.repo.ts
> +    getByfirstName = async (firstName: string): Promise<InstructorDto> => {
remove if not used

2022-11-09 15:10 UTC, azoirov commented on src/domain/instructors/instructor.service.ts
> +        if(instructor) throw new BadRequestError(ErrorCode.InstructorAlreadyExists)
user ConflictError

2022-11-09 15:10 UTC, azoirov commented on src/domain/instructors/instructor.service.ts
> +    public InstructorRepo = new InstructorRepo()
public instructorRepo = new InstructorRepo()

2022-11-09 15:10 UTC, azoirov commented on src/domain/instructors/instructor.service.ts
> +    public getAll = async ():Promise<InstructorDto[]>  => {
return this.instructorRepo.getAll()

2022-11-09 15:10 UTC, azoirov commented on src/domain/instructors/instructor.service.ts
> +        const result = await this.InstructorRepo.getById(id)
const instructor = await this.instructorRepo.getById(id);

if(!instructor) throw new NotFoundError(ErrorCode.InsturctorNotFound)

return instructror

2022-11-09 15:10 UTC, azoirov commented on src/domain/instructors/instructor.service.ts
> +        const result = await this.InstructorRepo.update(id, updateData);
return this.intructorRepo.update(....)

2022-11-09 15:10 UTC, azoirov commented on src/domain/instructors/instructor.service.ts
> +        const result = await this.InstructorRepo.deleteById(id);
return this.instructorRepo.....

2022-11-11 02:16 UTC, azoirov commented on src/domain/instructors/instructor.service.ts
> +        if(instructor) throw new BadRequestError(ErrorCode.InstructorAlreadyExists)
bu ozgarmabti

2022-11-13 10:22 UTC, MubiynDev commented on src/domain/instructors/instructor.service.ts
> +        if(instructor) throw new BadRequestError(ErrorCode.InstructorAlreadyExists)
togrladim

2022-11-16 02:39 UTC, azoirov approved these changes

2022-11-16 02:42 UTC, merged